//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stms.SkmtrNormalizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stms.SkmtrNormalizer.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение данных из Excel....
        /// </summary>
        internal static string GetDataFromExcelException {
            get {
                return ResourceManager.GetString("GetDataFromExcelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ячейке &apos;{0}&apos; ожидается значение [&apos;{1}&apos;]. Фактическое значение - [&apos;{2}&apos;]. Имя файла - [&apos;{3}&apos;]; Имя листа - [&apos;{4}&apos;]..
        /// </summary>
        internal static string InvalidColumnNameException {
            get {
                return ResourceManager.GetString("InvalidColumnNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя листа &apos;{0}&apos; имеет некорректный формат: в имени листа нет признака принадлежности к материалам или запчастям .
        /// </summary>
        internal static string InvalidSheetNameException {
            get {
                return ResourceManager.GetString("InvalidSheetNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл готов по ссылке &apos;{0}&apos;. Нажмите любую клавишу для выхода....
        /// </summary>
        internal static string OutputXlsxFileReadyException {
            get {
                return ResourceManager.GetString("OutputXlsxFileReadyException", resourceCulture);
            }
        }
    }
}
